name: fuga_suffix
run-name: ${{ github.ref_name }} by @${{ github.actor }} at ${{ github.workflow }}
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Failure
        run: exit 1
