name: actionlint
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/**.yaml
jobs:
  actinlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v3.0.2
        with:
          aqua_version: v2.37.2
      - name: Install actionlint
        env:
          PATH: "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH"
        run: aqua install --tags actionlint
      - name: Run actionlint
        run: actionlint
