name: aqua
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  workflow_dispatch:
jobs:
  auto-creation-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version golangci-lint
        id: golangci-lint
        run: | 
          version=$(yq '.packages[]' aqua.yaml | grep 'golangci' | cut -d "@" -f 2)
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v${{ steps.golangci-lint.outputs.version }}
          args: --allow-parallel-runners
  