name: aqua
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  workflow_dispatch:
jobs:
  auto-creation-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.25.1
      - name: Install golangci-lint
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua install --tags golangci/golangci-lint
      - name: Run golangci-lint
        id: golangci-lint
        run: | 
          version=$(golangci-lint --version | awk '{print $4}')
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: ${{ steps.golangci-lint.outputs.version }}
          args: --allow-parallel-runners
  