name: create tag
run-name: ${{ github.ref_name }} by @${{ github.actor }} at ${{ github.workflow }}
on:
  workflow_dispatch:
jobs:
  tag:
    runs-on: ubuntu-22.04
    steps:
      - name: Create tag
        id: create-tag
        run: |
          TAG=`date +%Y-%m-%d-%H-%M-%S`
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Push tag
        run: |
          git tag ${{ steps.create-tag.outputs.tag }}
          git push origin ${{ steps.create-tag.outputs.tag }}
