name: create private issue
run-name: ${{ github.ref_name }} by @${{ github.actor }} at ${{ github.workflow }}
on:
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      creatable: ${{ steps.check-diff.outputs.creatable }}
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
            app-id: ${{ secrets.BOT_GITHUB_APP_ID }}
            private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: otakakot/dailyreport
          token: ${{ steps.generate-token.outputs.token }}
      - name: Check diff
        id: check-diff
        run: |
          gh issue create --title "test" --body "test"
