name: cron
run-name: ${{ github.ref_name }} by @${{ github.actor }} at ${{ github.workflow }}
on:
  workflow_dispatch:
#  schedule:
#    - cron: '*/10 * * * *'
jobs:
  schedule_cron:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check
        id: check
        # 理想はここでジョブの実行をチェックして実行が終了したかどうかのフラグを立てる
        run: echo "done=true" >> "$GITHUB_OUTPUT"
      - name: Generate token
        if: ${{ steps.check.outputs.done }}
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Repository dispatch
        if: ${{ steps.check.outputs.done }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: ${{ github.repository }}
          event-type: disable
