name: cron enable
run-name: ${{ github.ref_name }} by @${{ github.actor }} at ${{ github.workflow }}
on:
  workflow_dispatch:
jobs:
  enable:
    runs-on: ubuntu-22.04
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Enable
        env:
          GH_USER_EMAIL: 126062861+otakakot-bot[bot]@users.noreply.github.com
          GH_USER_NAME: otakakot-bot[bot]
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          ./script/enable.sh ./.github/workflows/cron.yaml
          diff=$(git diff ./.github/workflows/cron.yaml)
          if [[ -n "${diff}" ]]; then
            git config --global user.email ${{ env.GH_USER_EMAIL }}
            git config --global user.name ${{ env.GH_USER_NAME }}
            git add ./.github/workflows/cron.yaml
            git commit -m "enable"
            git push
          fi
