name: cron go mod update
run-name: ${{ github.ref_name }} by @${{ github.actor }} at ${{ github.workflow }}
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'
jobs:
  schedule_cron:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Go mod update
        id: go-mod-update
        run: |
          go get -u -t ./...
          go mod tidy
          echo "diff=$(git status --short | wc -l)" >> $GITHUB_OUTPUT
      - name: Create PR
        if: ${{ steps.go-mod-update.outputs.diff > 0 }}
        env:
            GH_USER_EMAIL: 126062861+otakakot[bot]@users.noreply.github.com
            GH_USER_NAME: otakakot[bot]
            GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          git branch feature/gomod
          git switch feature/gomod
          git config --global user.email ${{ env.GH_USER_EMAIL }}
          git config --global user.name ${{ env.GH_USER_NAME }}
          git add .
          git commit -m "update go.mod"
          git push --set-upstream origin feature/gomod
          gh pr create --title "Update go.mod" --body "update go.mod" --base main --head feature/gomod
