name: go version
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  pull_request:
    paths:
      - .github/workflows/go.version.yaml
jobs:
  version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: core/go.mod
          check-latest: true
      - name: Go version
        run: |
            GO_VERSION=$(go version | awk '{print $3}' | cut -c 3-)
            echo "${GO_VERSION}"
            echo "${GOVERSION}"
