name: installed packages

on:
  push:
    branches:
      - main

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
    - name: List packages
      run: dpkg -l | grep ^ii
    - name: yq
      run: yq --version
