name: job trigger
run-name: ${{ github.ref_name }} by @${{ github.actor }} at ${{ github.workflow }}
on:
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trigger
        run: echo "trigger"
      - name: Check
        run: |
          count=1
          while [[ true ]] ; do
            if [[ ${count} -gt 3 ]]; then
              echo "timeout"
              exit 1
            fi
            count=$((count + 1))
            sleep 60
          done
          echo "done"
