name: mask secret
run-name: ${{ github.ref_name }} by @${{ github.actor }} at ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "environment"
        required: true
        options:
          - development
          - production
defaults:
  run:
    shell: bash
jobs:
  playground:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup Secret
        id: secret
        env:
          SECRET: |-
            ${{ fromJSON('{
              "development": "secrets.DEVELOPMENT_SECRET",
              "production": "secrets.PRODUCTION_SECRET"
            }')[inputs.environment] }}
        run: |
          secret=${SECRET}
          echo "::add-mask::${secret}"
          echo "secret=${secret}" >> $GITHUB_OUTPUT
      - name: echo
        run: echo ${{ steps.secret.outputs.secret }}
