name: mask secret
run-name: ${{ github.ref_name }} by @${{ github.actor }} at ${{ github.workflow }}
on:
  workflow_dispatch:
jobs:
  playground:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 5
    steps:
      - name: Setup Secret
        id: secret
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          secret=${SECRET}
          echo "::add-mask::${secret}"
          echo "secret=${secret}" >> $GITHUB_OUTPUT
      - name: echo
        run: echo ${{ steps.secret.outputs.secret }}
