name: merged pr
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    types:
      - closed
defaults:
  run:
    shell: bash
jobs:
  if-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check branch
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          echo ${{ env.HEAD_REF }}
          echo "hoge"
