name: merged pr
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    types:
      - closed
defaults:
  run:
    shell: bash
jobs:
  if-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check PR
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: |
          echo ${{ github.event.pull_request.labels }}
          echo "hoge"
