name: pull request edited
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    paths:
      - .github/workflows/pull.request.edited.yaml
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          echo ${{ env.HEAD_REF }}
          echo "hoge"
