name: pull request
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    paths:
      - README.md
jobs:
  pull-request:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 5
    steps:
      - name: Check branch
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          echo ${{ env.HEAD_REF }}
          echo "hoge"
