name: workflow
run-name: ${{ github.ref_name }} by @${{ github.actor }} at ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "environment"
        required: true
        options:
          - develop
          - preview
          - production
      name:
        type: string
        description: "name"
        required: true
      flag:
        type: boolean
        description: "flag"
        required: true
        default: false
jobs:
  workflow_dispatch:
    runs-on: ubuntu-22.04
    env:
      ENV: |-
        ${{ fromJSON('{
          "develop": "dev",
          "preview": "prev",
          "production": "prod"
        }')[github.event.inputs.environment] }}
    steps:
      - name: Display environment
        run: |
          echo "environment: ${{ github.event.inputs.environment }}"
          echo "env: ${{ env.ENV }}"
      - name: Check name
        run: |
          if [[ -z "${{ inputs.name }}" ]]; then
            echo "name is empty"
            exit 1
          fi
