name: retry
run-name: ${{ github.ref_name }} by @${{ github.actor }} at ${{ github.workflow }}
on:
  workflow_run:
    workflows:
      - "*_suffix"
    types:
      - completed
defaults:
  run:
    shell: bash
jobs:
  prepare:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    timeout-minutes: 5
    steps:
      - name: echo ${{ github.event.workflow_run.id }}
        run:
            echo ${{ github.event.workflow_run.id }}
